"Subject"                  "Activity"                 "XTimeBody_acc_mean"       "YTimeBody_acc_mean"       "ZTimeBody_acc_mean"      
"XTimeBody_acc_std"        "YTimeBody_acc_std"        "ZTimeBody_acc_std"        "XTimeGravity_acc_mean"    "YTimeGravity_acc_mean"   
 "ZTimeGravity_acc_mean"    "XTimeGravity_acc_std"     "YTimeGravity_acc_std"     "ZTimeGravity_acc_std"     "XTimeBodyAccJerk_mean"   
 "YTimeBodyAccJerk_mean"    "ZTimeBodyAccJerk_mean"    "XTimeBodyAccJerk_std"     "YTimeBodyAccJerk_std"     "ZTimeBodyAccJerk_std"    
 "XTimeBodyGyro_mean"       "YTimeBodyGyro_mean"       "ZTimeBodyGyro_mean"       "XTimeBodyGyro_std"        "YTimeBodyGyro_std"       
 "ZTimeBodyGyro_std"        "XTimeBodyGyroJerk_mean"   "YTimeBodyGyroJerk_mean"   "ZTimeBodyGyroJerk_mean"   "XTimeBodyGyroJerk_std"   
 "YTimeBodyGyroJerk_std"    "ZTimeBodyGyroJerk_std"    "TimeBodyAccMag_mean"      "TimeBodyAccMag_std"       "TimeGravityAccMag_mean"  
 "TimeGravityAccMag_std"    "TimeBodyAccJerkMag_mean"  "TimeBodyAccJerkMag_std"   "TimeBodyGyroMag_mean"     "TimeBodyGyroMag_std"     
 "TimeBodyGyroJerkMag_mean" "TimeBodyGyroJerkMag_std"  "XFreqBodyAcc_mean"        "YFreqBodyAcc_mean"        "ZFreqBodyAcc_mean"       
"XFreqBodyAcc_std"         "YFreqBodyAcc_std"         "ZFreqBodyAcc_std"         "XFreqBodyAccJerk_mean"    "YFreqBodyAccJerk_mean"   
 "ZFreqBodyAccJerk_mean"    "XFreqBodyAccJerk_std"     "YFreqBodyAccJerk_std"     "ZFreqBodyAccJerk_std"     "XFreqBodyGyro_mean"      
 "YFreqBodyGyro_mean"       "ZFreqBodyGyro_mean"       "XFreqBodyGyro_std"        "YFreqBodyGyro_std"        "ZFreqBodyGyro_std"       
 "FreqBodyAccMag_mean"      "FreqBodyAccMag_std"       "FreqBodyAccJerkMag_mean"  "FreqBodyAccJerkMag_std"   "FreqBodyGyroMag_mean"    
"FreqBodyGyroMag_std"      "FreqBodyGyroMagJerk_mean" "FreqBodyGyroMagJerk_std"